package eu.winwinit.bcc.entities;
// Generated 2-ott-2019 9.39.22 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Filiali generated by hbm2java
 */
@Entity
@Table(name = "filiali", catalog = "bcc")
public class Filiali implements java.io.Serializable {

	private Integer id;
	private String nome;
	private Integer codice;
	private String cab;
	private ArrayList<Clienti> clienti = new ArrayList<Clienti>();
	private ArrayList<Utenti> utenti = new ArrayList<Utenti>();

	public Filiali() {
	}

	public Filiali(String nome, String cab) {
		this.nome = nome;
		this.cab = cab;
	}

	public Filiali(String nome, Integer codice, String cab, ArrayList<Clienti> clienti, ArrayList<Utenti> utenti) {
		this.nome = nome;
		this.codice = codice;
		this.cab = cab;
		this.clienti = clienti;
		this.utenti = utenti;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 40)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "codice")
	public Integer getCodice() {
		return this.codice;
	}

	public void setCodice(Integer codice) {
		this.codice = codice;
	}

	@Column(name = "cab", nullable = false, length = 5)
	public String getCab() {
		return this.cab;
	}

	public void setCab(String cab) {
		this.cab = cab;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filiali")
	public ArrayList<Clienti> getClienti() {
		return this.clienti;
	}

	public void setClienti(ArrayList<Clienti> clienti) {
		this.clienti = clienti;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filiali")
	public ArrayList<Utenti> getUtenti() {
		return this.utenti;
	}

	public void setUtenti(ArrayList<Utenti> utenti) {
		this.utenti = utenti;
	}

}
