package eu.winwinit.bcc.entities;
// Generated 2-ott-2019 9.39.22 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RuoliUtenti generated by hbm2java
 */
@Entity
@Table(name = "ruoli_utenti", catalog = "bcc", uniqueConstraints = @UniqueConstraint(columnNames = "ruolo"))
public class RuoliUtenti implements java.io.Serializable {

	private Integer id;
	private String ruolo;
	private ArrayList<Utenti> utenti = new ArrayList<Utenti>();

	public RuoliUtenti() {
	}

	public RuoliUtenti(String ruolo) {
		this.ruolo = ruolo;
	}

	public RuoliUtenti(String ruolo, ArrayList<Utenti> utenti) {
		this.ruolo = ruolo;
		this.utenti = utenti;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ruolo", unique = true, nullable = false, length = 20)
	public String getRuolo() {
		return this.ruolo;
	}

	public void setRuolo(String ruolo) {
		this.ruolo = ruolo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ruoliUtenti")
	public ArrayList<Utenti> getUtenti() {
		return this.utenti;
	}

	public void setUtenti(ArrayList<Utenti> utenti) {
		this.utenti = utenti;
	}

}
