package eu.winwinit.bcc.entities;
// Generated 1-ott-2019 15.44.52 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Utenti generated by hbm2java
 */
@Entity
@Table(name = "utenti", catalog = "bcc", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class Utenti implements java.io.Serializable {

	private Integer id;
	private Filiali filiali;
	private String username;
	private String nome;
	private String cognome;
	private String password;
	private Boolean statoAttivo;
	private Boolean cambioPassword;

	public Utenti() {
	}

	public Utenti(Filiali filiali, String username, String password) {
		this.filiali = filiali;
		this.username = username;
		this.password = password;
	}

	public Utenti(Filiali filiali, String username, String nome, String cognome, String password, Boolean statoAttivo,
			Boolean cambioPassword) {
		this.filiali = filiali;
		this.username = username;
		this.nome = nome;
		this.cognome = cognome;
		this.password = password;
		this.statoAttivo = statoAttivo;
		this.cambioPassword = cambioPassword;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_filiale", nullable = false)
	public Filiali getFiliali() {
		return this.filiali;
	}

	public void setFiliali(Filiali filiali) {
		this.filiali = filiali;
	}

	@Column(name = "username", unique = true, nullable = false, length = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "nome", length = 30)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "cognome", length = 30)
	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	@Column(name = "password", nullable = false, length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "stato_attivo")
	public Boolean getStatoAttivo() {
		return this.statoAttivo;
	}

	public void setStatoAttivo(Boolean statoAttivo) {
		this.statoAttivo = statoAttivo;
	}

	@Column(name = "cambio_password")
	public Boolean getCambioPassword() {
		return this.cambioPassword;
	}

	public void setCambioPassword(Boolean cambioPassword) {
		this.cambioPassword = cambioPassword;
	}

}
